File.truncate(length) requires a parameter
1.9.2p180 :025 >     f = File.open("destroy_this_file", "w")
 => #<File:destroy_this_file>
1.9.2p180 :026 >     f.truncate
ArgumentError: wrong number of arguments(0 for 1)
	from (irb):26:in `truncate'